name: 部署 Zola 网站到 GitHub Pages

on:
  push:
    branches:
      - main  # 设置为你的默认分支

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 构建和部署
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # 你必须设置 GITHUB_TOKEN 环境变量
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # 如果你使用自定义域名，取消下面一行的注释并修改为你的域名
          # DOMAIN: example.com
          # 如果你想使用不同的分支作为发布分支，取消下面一行的注释并修改
          PAGES_BRANCH: gh-pages
